import './globals.css'
import { Inter } from 'next/font/google'
// import Home from './Home/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        {/* <nav>
          <ul>
            <li>
            <a href="/">Home</a>
            </li>
            <li>
            <a href="/about">About</a>
            </li>
          </ul>
        </nav> */}
      {/* <Home /> */}
    {children}</body>
    </html>
  )
}
